version: '3'

services:

  redis:
    container_name: orchidae_redis_dev
    image: redis:${REDIS_VERSION}
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./config/redis:/usr/local/etc/redis:ro
    command: bash -c  "sed -e \"s/{PASSWORD}/${REDIS_PASSWORD}/g\" < /usr/local/etc/redis/redis.conf | redis-server -"
  mongodb:
    container_name: orchidae_mongo_dev
    image: mongo:${MONGO_VERSION}
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
