version: '2'

services:

  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./config/redis:/usr/local/etc/redis
    command: bash -c  "sed -e \"s/{PASSWORD}/$PASSWRD/g\" < /usr/local/etc/redis/redis.conf | redis-server -"
  mongodb:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
