version: '3'

services:

  redis:
    container_name: orchidae_redis_dev
    image: redis:${REDIS_VERSION}
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./config/redis:/usr/local/etc/redis:ro
    command: bash -c  "sed -e \"s/{PASSWORD}/${REDIS_PASSWORD}/g\" < /usr/local/etc/redis/redis.conf | redis-server -"
  mongodb:
    container_name: orchidae_mongo_dev
    image: mongo:${MONGO_VERSION}
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  config:
    build: ./config-server
    container_name: orchidae_config
    ports:
    - "8888:8888"
    volumes:
    - ../orchidae-config:/cluster-config
    environment:
    - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=file:/cluster-config
    restart:
      unless-stopped
  discovery-service:
    build: ./discovery-server
    container_name: orchidae-discovery
    ports:
    - "8761:8761"
    tty:
      true
    restart:
      unless-stopped
  admin-server:
    build: ./admin-server
    ports:
    - "8092:8092"
    environment:
    - REGISTRY_HOST=orchidae-discovery
    tty:
      true
    restart:
      unless-stopped
