spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file:../../orchidae-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
server:
  port: 8888
